CREATE TABLE `data_duration_stats` (
  `master_id` varchar(100) NOT NULL,
  `function_exec_stats_id` int(11) NOT NULL,
  `ed_indata_min` double DEFAULT NULL,
  `ed_indata_max` double DEFAULT NULL,
  `ed_indata_mean` double DEFAULT NULL,
  `ed_indata_median` double DEFAULT NULL,
  `ed_indata_variance` double DEFAULT NULL,
  `fog_indata_min` double DEFAULT NULL,
  `fog_indata_max` double DEFAULT NULL,
  `fog_indata_mean` double DEFAULT NULL,
  `fog_indata_median` double DEFAULT NULL,
  `fog_indata_variance` double DEFAULT NULL,
  `edge_indata_min` double DEFAULT NULL,
  `edge_indata_max` double DEFAULT NULL,
  `edge_indata_mean` double DEFAULT NULL,
  `edge_indata_median` double DEFAULT NULL,
  `edge_indata_variance` double DEFAULT NULL,
  `core_indata_min` double DEFAULT NULL,
  `core_indata_max` double DEFAULT NULL,
  `core_indata_mean` double DEFAULT NULL,
  `core_indata_median` double DEFAULT NULL,
  `core_indata_variance` double DEFAULT NULL,
  `ed_outdata_min` double DEFAULT NULL,
  `ed_outdata_max` double DEFAULT NULL,
  `ed_outdata_mean` double DEFAULT NULL,
  `ed_outdata_median` double DEFAULT NULL,
  `ed_outdata_variance` double DEFAULT NULL,
  `fog_outdata_min` double DEFAULT NULL,
  `fog_outdata_max` double DEFAULT NULL,
  `fog_outdata_mean` double DEFAULT NULL,
  `fog_outdata_median` double DEFAULT NULL,
  `fog_outdata_variance` double DEFAULT NULL,
  `edge_outdata_min` double DEFAULT NULL,
  `edge_outdata_max` double DEFAULT NULL,
  `edge_outdata_mean` double DEFAULT NULL,
  `edge_outdata_median` double DEFAULT NULL,
  `edge_outdata_variance` double DEFAULT NULL,
  `core_outdata_min` double DEFAULT NULL,
  `core_outdata_max` double DEFAULT NULL,
  `core_outdata_mean` double DEFAULT NULL,
  `core_outdata_median` double DEFAULT NULL,
  `core_outdata_variance` double DEFAULT NULL,
  PRIMARY KEY (`master_id`,`function_exec_stats_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_size_stats` (
  `master_id` varchar(100) NOT NULL,
  `function_exec_stats_id` int(11) NOT NULL,
  `ed_indata_min` double DEFAULT NULL,
  `ed_indata_max` double DEFAULT NULL,
  `ed_indata_mean` double DEFAULT NULL,
  `ed_indata_median` double DEFAULT NULL,
  `ed_indata_variance` double DEFAULT NULL,
  `fog_indata_min` double DEFAULT NULL,
  `fog_indata_max` double DEFAULT NULL,
  `fog_indata_mean` double DEFAULT NULL,
  `fog_indata_median` double DEFAULT NULL,
  `fog_indata_variance` double DEFAULT NULL,
  `edge_indata_min` double DEFAULT NULL,
  `edge_indata_max` double DEFAULT NULL,
  `edge_indata_mean` double DEFAULT NULL,
  `edge_indata_median` double DEFAULT NULL,
  `edge_indata_variance` double DEFAULT NULL,
  `core_indata_min` double DEFAULT NULL,
  `core_indata_max` double DEFAULT NULL,
  `core_indata_mean` double DEFAULT NULL,
  `core_indata_median` double DEFAULT NULL,
  `core_indata_variance` double DEFAULT NULL,
  `ed_outdata_min` double DEFAULT NULL,
  `ed_outdata_max` double DEFAULT NULL,
  `ed_outdata_mean` double DEFAULT NULL,
  `ed_outdata_median` double DEFAULT NULL,
  `ed_outdata_variance` double DEFAULT NULL,
  `fog_outdata_min` double DEFAULT NULL,
  `fog_outdata_max` double DEFAULT NULL,
  `fog_outdata_mean` double DEFAULT NULL,
  `fog_outdata_median` double DEFAULT NULL,
  `fog_outdata_variance` double DEFAULT NULL,
  `edge_outdata_min` double DEFAULT NULL,
  `edge_outdata_max` double DEFAULT NULL,
  `edge_outdata_mean` double DEFAULT NULL,
  `edge_outdata_median` double DEFAULT NULL,
  `edge_outdata_variance` double DEFAULT NULL,
  `core_outdata_min` double DEFAULT NULL,
  `core_outdata_max` double DEFAULT NULL,
  `core_outdata_mean` double DEFAULT NULL,
  `core_outdata_median` double DEFAULT NULL,
  `core_outdata_variance` double DEFAULT NULL,
  PRIMARY KEY (`master_id`,`function_exec_stats_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `function_exec_stats` (
  `id` int(11) NOT NULL,
  `master_id` varchar(100) NOT NULL,
  `execution_location` int(11) NOT NULL,
  `function_feature_id` int(19) NOT NULL,
  `running_duration_min` double DEFAULT NULL,
  `running_duration_max` double DEFAULT NULL,
  `running_duration_mean` double DEFAULT NULL,
  `running_duration_median` double DEFAULT NULL,
  `running_duration_variance` double DEFAULT NULL,
  `processing_duration_min` double DEFAULT NULL,
  `processing_duration_max` double DEFAULT NULL,
  `processing_duration_mean` double DEFAULT NULL,
  `processing_duration_median` double DEFAULT NULL,
  `processing_duration_variance` double DEFAULT NULL,
  `completion_duration_min` double DEFAULT NULL,
  `completion_duration_max` double DEFAULT NULL,
  `completion_duration_mean` double DEFAULT NULL,
  `completion_duration_median` double DEFAULT NULL,
  `completion_duration_variance` double DEFAULT NULL,
  `function_request_min` double DEFAULT NULL,
  `function_request_max` double DEFAULT NULL,
  `function_request_mean` double DEFAULT NULL,
  `function_request_median` double DEFAULT NULL,
  `function_request_variance` double DEFAULT NULL,
  `function_response_min` double DEFAULT NULL,
  `function_response_max` double DEFAULT NULL,
  `function_response_mean` double DEFAULT NULL,
  `function_response_median` double DEFAULT NULL,
  `function_response_variance` double DEFAULT NULL,
  PRIMARY KEY (`id`,`master_id`,`execution_location`,`function_feature_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `function_feature` (
  `id` int(19) NOT NULL AUTO_INCREMENT,
  `function_profile_id` varchar(100) NOT NULL,
  `grade` int(11) NOT NULL,
  `master_id` varchar(100) NOT NULL,
  `maximum_completion_duration` double DEFAULT NULL,
  `unit_slo_violation_cost` double DEFAULT NULL,
  `number_of_cpu_cores` int(11) DEFAULT NULL,
  `size_of_memory` double DEFAULT NULL,
  PRIMARY KEY (`id`,`grade`,`function_profile_id`,`master_id`)
) ENGINE=InnoDB AUTO_INCREMENT=502 DEFAULT CHARSET=utf8;

CREATE TABLE `function_instance_info` (
  `master_id` varchar(100) NOT NULL,
  `id` int(19) NOT NULL AUTO_INCREMENT,
  `node_group_type` int(11) DEFAULT NULL,
  `function_profile_id` varchar(100) DEFAULT NULL,
  `maximum_completion_duration` int(11) DEFAULT NULL,
  `function_request_time` double DEFAULT NULL,
  `function_completion_time` double DEFAULT NULL,
  `function_starting_time` double DEFAULT NULL,
  `function_running_duration` double DEFAULT NULL,
  `function_processing_duration` double DEFAULT NULL,
  `delay_violation` varchar(1) DEFAULT NULL,
  `function_use_cpu_core_size` int(11) DEFAULT NULL,
  `function_use_memory_size` int(11) DEFAULT NULL,
  `function_use_processing_mi_size` int(11) DEFAULT NULL,
  `function_request_message_size` double DEFAULT NULL,
  `function_response_message_size` double DEFAULT NULL,
  `sensor_id` int(11) DEFAULT NULL,
  `actuator_id` int(11) DEFAULT NULL,
  `violation_unit_cost` double DEFAULT NULL,
  `snapshot_id` decimal(19,0) DEFAULT NULL,
  `total_cost` double DEFAULT NULL,
  `violation_cost` double DEFAULT NULL,
  `computing_cost` double DEFAULT NULL,
  `input_data_networking_cost` double DEFAULT NULL,
  `output_data_networking_cost` double DEFAULT NULL,
  `input_data_reading_duration` double DEFAULT NULL,
  `output_data_writing_duration` double DEFAULT NULL,
  `function_instance_id` varchar(100) NOT NULL,
  PRIMARY KEY (`id`,`master_id`,`function_instance_id`)
) ENGINE=InnoDB AUTO_INCREMENT=86236 DEFAULT CHARSET=utf8;

CREATE TABLE `master` (
  `id` varchar(100) NOT NULL,
  `create_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `node_group_resource_usage_state` (
  `master_id` varchar(100) NOT NULL,
  `id` int(19) NOT NULL,
  `node_group_type` int(11) DEFAULT NULL,
  `time_stamp` varchar(45) DEFAULT NULL,
  `total_cpu` int(11) DEFAULT NULL,
  `total_memory` int(11) DEFAULT NULL,
  PRIMARY KEY (`master_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `node_group_resource_usage_state_detail` (
  `master_id` varchar(100) NOT NULL,
  `resource_usage_state_id` int(11) NOT NULL,
  `type` varchar(45) NOT NULL,
  `boundary` varchar(45) NOT NULL,
  `value` double DEFAULT NULL,
  PRIMARY KEY (`master_id`,`resource_usage_state_id`,`type`,`boundary`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
